zookeeper:
  build: ./zookeeper
  container_name: dps-zookeeper
  hostname: zookeeper
  ports:
    - "2181:2181"
elasticsearch:
  image: elasticsearch:2.2.1
  container_name: dps-elasticsearch
  command: elasticsearch -Des.network.host=0.0.0.0
  hostname: elasticsearch
  ports:
      - "9200:9200"
      - "9300:9300"
logstash:
  image: logstash:2.2.2
  hostname: logstash
  container_name: dps-logstash
  command: logstash -f /etc/logstash/conf.d/logstash.conf
  volumes:
    - ./logstash/config:/etc/logstash/conf.d
  ports:
    - "5000:5000"
  expose:
    - "5000"
  links:
    - elasticsearch
    - zookeeper
kibana:
  build: ./kibana/
  container_name: dps-kibana
  hostname: kibana
  volumes:
    - ./kibana/config/:/opt/kibana/config/
  ports:
    - "5601:5601"
  links:
    - elasticsearch
proxy:
  build: ./proxy
  container_name: dps-proxy
  ports:
    - "8082:8080"
    - "8081:8081"
    - "80:80"
  links:
    - zookeeper
    - logstash
    - zabbix
  volumes:
    - ./proxy/config:/etc/traefik/
dynamo:
  build: ./dynamo
  links:
    - zookeeper
#    - logstash
#    - zabbix
zabbix:
  image: berngp/docker-zabbix
  container_name: dps-zabbix
  hostname: zabbix
  ports:
      - "10051:10051"
      - "10052:10052"
      - "8089:80"
      - "2812:2812"