version: '2'
services:
  zookeeper:
    build: ./zookeeper
    container_name: dps-zookeeper
    hostname: zookeeper
    ports:
      - "2181:2181"
  elasticsearch:
    build: ./elasticsearch
    container_name: dps-elasticsearch
    command: elasticsearch -Des.network.host=0.0.0.0
    hostname: elasticsearch
    ports:
        - "9200:9200"
        - "9300:9300"
  logstash:
    build: ./logstash
    hostname: logstash
    container_name: dps-logstash
    command: logstash -f /etc/logstash/conf.d/logstash.conf
    ports:
      - "5000:5000"
    expose:
      - "5000"
  kibana:
    build: ./kibana/
    container_name: dps-kibana
    hostname: kibana
    ports:
      - "5601:5601"
  proxy:
    build: ./proxy
    container_name: dps-proxy
    ports:
      - "8082:8080"
      - "8081:8081"
      - "80:80"
    volumes:
      - ./proxy/config:/etc/traefik/
  dynamo:
    build: ./dynamo
      zabbix:
        image: berngp/docker-zabbix
        container_name: dps-zabbix
        hostname: zabbix
        ports:
            - "10051:10051"
            - "10052:10052"
            - "8089:80"
            - "2812:2812"
networks:
  default:
    external:
      name: DPS
