zookeeper:
  build: ./zookeeper
  container_name: dps-zookeeper
  hostname: zookeeper.dev
  domainname: zookeeper.dev
  ports:
    - "2181:2181"
  links:
    - "traefik"
#dynamo:
#  build: ./dynamo
#  container_name: dynamo
#  ports:
#    - "8080:8080"
elasticsearch:
  image: elasticsearch:2.2.1
  container_name: dps-elasticsearch
  command: elasticsearch -Des.network.host=0.0.0.0
  ports:
      - "9200:9200"
      - "9300:9300"
logstash:
  image: logstash:2.2.2
  container_name: dps-logstash
  command: logstash -f /etc/logstash/conf.d/logstash.conf
  volumes:
    - ./logstash/config:/etc/logstash/conf.d
  ports:
    - "5000:5000"
  links:
    - elasticsearch
kibana:
  build: ./kibana/
  container_name: dps-kibana
  volumes:
    - ./kibana/config/:/opt/kibana/config/
  ports:
    - "5601:5601"
  links:
    - elasticsearch