################################################################
# Web configuration backend
################################################################
[web]
address = ":8080"

################################################################
# Zookeeper configuration backend
################################################################
[zookeeper]
endpoint = "172.17.0.3:2181"
watch = true
prefix = "/traefik"
# filename = "zookeeper.tmpl"

################################################################
# Global configuration
################################################################

defaultEntryPoints = ["http", "https"]
[entryPoints]
  [entryPoints.http]
  address = ":80"
  [entryPoints.https]
  address = ":443"

graceTimeOut = 10

# Traefik logs file
# If not defined, logs to stdout
#
# Optional
#
traefikLogsFile = "log/traefik.log"

# Access logs file
#
# Optional
#
accessLogsFile = "log/access.log"

# Log level
logLevel = "DEBUG"

# Backends throttle duration: minimum duration between 2 events from providers
# before applying a new configuration. It avoids unnecessary reloads if multiples events
# are sent in a short amount of time.
#
# Optional
# Default: "2s"
#
# ProvidersThrottleDuration = "5s"

# If non-zero, controls the maximum idle (keep-alive) to keep per-host.  If zero, DefaultMaxIdleConnsPerHost is used.
# If you encounter 'too many open files' errors, you can either change this value, or change `ulimit` value.
#
# Optional
# Default: http.DefaultMaxIdleConnsPerHost
#
# MaxIdleConnsPerHost = 200

[file]
[backends]
  [backends.dynamo]
    [backends.dynamo.LoadBalancer]
      method = "drr"
    [backends.dynamo.servers.server1]
    url = "http://172.17.0.1:8080"
    weight = 1
    [backends.dynamo.servers.server2]
    url = "http://www.azet.sk"
    weight = 1
    [backends.dynamo.servers.server3]
    url = "http://www.google.sk"
    weight = 1

[frontends]
  [frontends.frontend1]
  entrypoints = ["http"]
  backend = "dynamo"