################################################################
# Web configuration backend
################################################################
[web]
address = ":8080"

################################################################
# Zookeeper configuration backend
################################################################
[zookeeper]
endpoint = "zookeeper.dev"
watch = true
prefix = "/traefik"